name: organdonation
description: A new Flutter project.
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
 
dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.2
  introduction_screen: ^1.0.9
  simple_animations: ^1.3.3
  flutter_app_name: ^0.1.0  
  introduction_slider: ^2.0.1
  google_fonts: ^3.0.1
  google_fonts_arabic: ^1.1.7
  smooth_page_indicator: ^1.0.0+2
  dropdown_button2: ^1.9.2
  intl: ^0.18.0
  animated_notch_bottom_bar: ^0.0.6
  font_awesome_flutter: ^10.3.0
  url_launcher: ^5.2.7
  file_picker: ^5.2.4
  flushbar: ^1.10.4 
  http: any
  dio: any
  http_parser: ^4.0.1
  pdf: ^3.8.4
  open_file: ^2.1.1


flutter_app_name:
  name: "Organ Donation"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

 
  flutter_lints: ^2.0.0
 
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" 
flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:  
  assets:
    - assets/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
